### Resources:
- [Lecture 7 - Introduction to TensorFlow](https://www.youtube.com/watch?v=L8Y2_Cq2X5s&list=PLmImxx8Char9Ig0ZHSyTqGsdhb9weEGam&index=7)
- [TensorFlow How Tos - Variables](https://www.tensorflow.org/versions/r0.10/how_tos/variables/index.html)
- Tensors can only hold one data type, have a shape and a rank (units of dimensionality) and are the only things that can be passed between operations in the computational graph. 

# Table of Contents
 <p><div class="lev3 toc-item"><a href="#Resources:" data-toc-modified-id="Resources:-0.0.1"><span class="toc-item-num">0.0.1&nbsp;&nbsp;</span>Resources:</a></div><div class="lev1 toc-item"><a href="#class-tf.Tensor" data-toc-modified-id="class-tf.Tensor-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>class tf.Tensor</a></div><div class="lev2 toc-item"><a href="#Info" data-toc-modified-id="Info-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Info</a></div><div class="lev2 toc-item"><a href="#Constants" data-toc-modified-id="Constants-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Constants</a></div><div class="lev3 toc-item"><a href="#=-tf.constant()..." data-toc-modified-id="=-tf.constant()...-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>= tf.constant()...</a></div><div class="lev3 toc-item"><a href="#=-tf.ones()..." data-toc-modified-id="=-tf.ones()...-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>= tf.ones()...</a></div><div class="lev2 toc-item"><a href="#Sequences" data-toc-modified-id="Sequences-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Sequences</a></div><div class="lev3 toc-item"><a href="#=-tf.linspace()..." data-toc-modified-id="=-tf.linspace()...-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>= tf.linspace()...</a></div><div class="lev2 toc-item"><a href="#Random" data-toc-modified-id="Random-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Random</a></div><div class="lev3 toc-item"><a href="#=-tf.random_normal()..." data-toc-modified-id="=-tf.random_normal()...-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>= tf.random_normal()...</a></div><div class="lev1 toc-item"><a href="#Variables" data-toc-modified-id="Variables-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Variables</a></div><div class="lev3 toc-item"><a href="#=-tf.placeholder()..." data-toc-modified-id="=-tf.placeholder()...-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>= tf.placeholder()...</a></div><div class="lev3 toc-item"><a href="#=-tf.Variable()..." data-toc-modified-id="=-tf.Variable()...-2.0.2"><span class="toc-item-num">2.0.2&nbsp;&nbsp;</span>= tf.Variable()...</a></div><div class="lev1 toc-item"><a href="#Shape" data-toc-modified-id="Shape-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Shape</a></div><div class="lev3 toc-item"><a href="#=-tf.Variable.get_shape()..." data-toc-modified-id="=-tf.Variable.get_shape()...-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span>= tf.Variable.get_shape()...</a></div><div class="lev3 toc-item"><a href="#=-tf.reshape()..." data-toc-modified-id="=-tf.reshape()...-3.0.2"><span class="toc-item-num">3.0.2&nbsp;&nbsp;</span>= tf.reshape()...</a></div><div class="lev4 toc-item"><a href="#+-Flatten-w/-[-1]..." data-toc-modified-id="+-Flatten-w/-[-1]...-3.0.2.1"><span class="toc-item-num">3.0.2.1&nbsp;&nbsp;</span>+ Flatten w/ [-1]...</a></div><div class="lev1 toc-item"><a href="#Casting" data-toc-modified-id="Casting-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Casting</a></div><div class="lev3 toc-item"><a href="#=-tf.convert_to_tensor()..." data-toc-modified-id="=-tf.convert_to_tensor()...-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span>= tf.convert_to_tensor()...</a></div><div class="lev2 toc-item"><a href="#dtypes" data-toc-modified-id="dtypes-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>dtypes</a></div><div class="lev3 toc-item"><a href="#=-tf.float32..." data-toc-modified-id="=-tf.float32...-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>= tf.float32...</a></div><div class="lev3 toc-item"><a href="#=-tf.uint8..." data-toc-modified-id="=-tf.uint8...-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>= tf.uint8...</a></div><div class="lev3 toc-item"><a href="#=-tf.string..." data-toc-modified-id="=-tf.string...-4.1.3"><span class="toc-item-num">4.1.3&nbsp;&nbsp;</span>= tf.string...</a></div><div class="lev1 toc-item"><a href="#Sharing" data-toc-modified-id="Sharing-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Sharing</a></div><div class="lev2 toc-item"><a href="#Scope" data-toc-modified-id="Scope-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Scope</a></div><div class="lev3 toc-item"><a href="#=-tf.variable_scope()..." data-toc-modified-id="=-tf.variable_scope()...-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>= tf.variable_scope()...</a></div><div class="lev3 toc-item"><a href="#=-tf.get_variable_scope()..." data-toc-modified-id="=-tf.get_variable_scope()...-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>= tf.get_variable_scope()...</a></div><div class="lev2 toc-item"><a href="#Variables" data-toc-modified-id="Variables-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Variables</a></div><div class="lev3 toc-item"><a href="#reuse_variables()" data-toc-modified-id="reuse_variables()-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>reuse_variables()</a></div><div class="lev3 toc-item"><a href="#=-tf.get_variable()..." data-toc-modified-id="=-tf.get_variable()...-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span>= tf.get_variable()...</a></div><div class="lev2 toc-item"><a href="#Initializers" data-toc-modified-id="Initializers-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Initializers</a></div><div class="lev3 toc-item"><a href="#=-tf.random_normal_initializer()..." data-toc-modified-id="=-tf.random_normal_initializer()...-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>= tf.random_normal_initializer()...</a></div><div class="lev3 toc-item"><a href="#Example" data-toc-modified-id="Example-5.3.2"><span class="toc-item-num">5.3.2&nbsp;&nbsp;</span>Example</a></div><div class="lev1 toc-item"><a href="#Device" data-toc-modified-id="Device-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Device</a></div><div class="lev3 toc-item"><a href="#=-tf.device()..." data-toc-modified-id="=-tf.device()...-6.0.1"><span class="toc-item-num">6.0.1&nbsp;&nbsp;</span>= tf.device()...</a></div>

In [3]:
# Import tensorflow
import tensorflow as tf

# class tf.Tensor
- [class tf.Tensor](https://www.tensorflow.org/versions/r0.11/api_docs/python/framework.html#Tensor)
- A Tensor is a symbolic handle to one of the outputs of an Operation. 
- It does not hold the values of that operation's output, but instead provides a means of computing those values in a TensorFlow Session.
- A Tensor can be passed as an input to another Operation.

## Info

In [ ]:
# The string name of this tensor.
tf.Tensor.name

In [ ]:
# The DType of elements in this tensor.
tf.Tensor.dtype

In [ ]:
# The Operation that produces this tensor as an output.
tf.Tensor.op

In [ ]:
# Returns a list of Operations that consume this tensor.
tf.Tensor.consumers()

In [ ]:
# The Graph that contains this tensor.
tf.Tensor.graph

In [ ]:
# Get the tensors shape
tf.Tensor.get_shape

## Constants

### = tf.constant()...
- [tf.constant(value, dtype=None, shape=None, name='Const')](https://www.tensorflow.org/versions/r0.11/api_docs/python/constant_op.html#constant)

In [6]:
# Constant Scaler
a = tf.constant(3, dtype=tf.float32, shape=[1,3,1])
print(a.get_shape)

with tf.Session() as sess:
    print(a.eval())

<bound method Tensor.get_shape of <tf.Tensor 'Const:0' shape=(1, 3, 1) dtype=float32>>
[[[ 3.]
  [ 3.]
  [ 3.]]]


In [7]:
# Constant 1-D Tensor populated with value list.
# Because there is 7 values in the list, our shape must total to 7
b = tf.constant([1, 2, 3, 4, 5, 6, 7], dtype=tf.float32, shape=[1,5,2])
print(b.get_shape)

with tf.Session() as sess:
    print(b.eval())

<bound method Tensor.get_shape of <tf.Tensor 'Const_1:0' shape=(1, 5, 2) dtype=float32>>
[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]
  [ 7.  7.]
  [ 7.  7.]]]


### = tf.ones()...
- [tf.zeros(shape, dtype=tf.float32, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/constant_op.html#ones)
- I like the ones() more than the zeros() because multiplying zeros sometimes kills the data.

In [2]:
# Matrix of ones
c = tf.ones([3, 4], dtype=tf.float32, name=None)
print(c.get_shape)

with tf.Session() as sess:
    print(c.eval())

<bound method Tensor.get_shape of <tf.Tensor 'ones:0' shape=(3, 4) dtype=float32>>
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [3]:
# Matrix of zeros
# I prefer working with ones
c = tf.zeros([4,1], dtype=tf.float32, name=None)
print(c.get_shape)

with tf.Session() as sess:
    print(c.eval())

<bound method Tensor.get_shape of <tf.Tensor 'zeros:0' shape=(4, 1) dtype=float32>>
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


## Sequences

### = tf.linspace()...

[tf.linspace(start, stop, num, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/constant_op.html#linspace)

In [5]:
# Generates values in an interval.
e = tf.linspace(3.0, -3.0, num=12, name=None)
print(e.get_shape)
e = tf.reshape(e, [12, 1])
print(e.get_shape)

with tf.Session() as sess:
    print(e.eval())

<bound method Tensor.get_shape of <tf.Tensor 'LinSpace:0' shape=(12,) dtype=float32>>
<bound method Tensor.get_shape of <tf.Tensor 'Reshape:0' shape=(12, 1) dtype=float32>>
[[ 3.        ]
 [ 2.4545455 ]
 [ 1.90909088]
 [ 1.36363626]
 [ 0.81818175]
 [ 0.27272725]
 [-0.27272749]
 [-0.81818199]
 [-1.36363649]
 [-1.909091  ]
 [-2.4545455 ]
 [-3.        ]]


## Random

### = tf.random_normal()...
- [tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/constant_op.html#random_normal)

In [4]:
# Matrix of zeros
d = tf.random_normal([4,3], mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
print(d.get_shape)

with tf.Session() as sess:
    print(d.eval())

<bound method Tensor.get_shape of <tf.Tensor 'random_normal:0' shape=(4, 3) dtype=float32>>
[[ 0.39460361  0.07359695  0.87660503]
 [ 0.80379128  0.75024688 -0.50730193]
 [ 0.10537744  0.21071444 -0.20797905]
 [-0.37804595  3.23810911  0.07111907]]


# Variables
- A variable maintains state in the graph across calls to run()
- A variable can have it's state updated between episodes

### = tf.placeholder()...
- [tf.placeholder(dtype, shape=None, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/io_ops.html#placeholder)

In [ ]:
# Placeholder
px = tf.placeholder(tf.float32,[None, 13], name="px")
py = tf.placeholder(tf.float32,[None, 1], name="py")

### = tf.Variable()...
- [tf.Variable( initial-value, name=optional-name )](https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#Variable)

In [12]:
w1_in = tf.Variable(tf.random_normal([N_FEATURES, N_NODES_H1]), name="w1")
b1_in = tf.Variable(tf.random_normal(shape=[N_NODES_H1, ]), name="b1")

<bound method Variable.get_shape of <tensorflow.python.ops.variables.Variable object at 0x119bb0fd0>>
<bound method Variable.get_shape of <tensorflow.python.ops.variables.Variable object at 0x119bb0eb8>>
<bound method Tensor.get_shape of <tf.Tensor 'Add:0' shape=(5, 2) dtype=float32>>
[[ 101.  101.]
 [ 101.  101.]
 [ 101.  101.]
 [ 101.  101.]
 [ 101.  101.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
100.0


# Shape

### = tf.Variable.get_shape()...
- [tf.Variable.get_shape()](https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html)

In [16]:
a.get_shape()

TensorShape([Dimension(1), Dimension(3), Dimension(1)])

In [20]:
# Get shape as list
a.get_shape().as_list()

[1, 3, 1]

In [21]:
# Get the shape as a list and return first value
a.get_shape().as_list()[0]

1

### = tf.reshape()...
- [tf.reshape(tensor, shape, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#reshape)

In [8]:
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a.get_shape)

with tf.Session() as sess:
    print(a.eval())

a = tf.reshape(a, [3, 3])
print(a.get_shape)

with tf.Session() as sess:
    print(a.eval())

<bound method Tensor.get_shape of <tf.Tensor 'Const_2:0' shape=(9,) dtype=int32>>
[1 2 3 4 5 6 7 8 9]
<bound method Tensor.get_shape of <tf.Tensor 'Reshape_1:0' shape=(3, 3) dtype=int32>>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### + Flatten w/ [-1]...

In [10]:
# Shape = [3, 2, 3]
c = tf.constant([[[1, 1, 1],
                  [2, 2, 2]],
                 [[3, 3, 3],
                  [4, 4, 4]],
                 [[5, 5, 5],
                  [6, 6, 6]]])

print(c.get_shape)

# pass '[-1]' to flatten
c = tf.reshape(c, [-1])

with tf.Session() as sess:
    print(c.eval())

<bound method Tensor.get_shape of <tf.Tensor 'Const_4:0' shape=(3, 2, 3) dtype=int32>>
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


# Casting

### = tf.convert_to_tensor()...
- [tf.convert_to_tensor(value, dtype=None, name=None, as_ref=False, preferred_dtype=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/framework.html#convert_to_tensor)
- This function converts Python objects of various types to Tensor objects. 
- It accepts Tensor objects, numpy arrays, Python lists, and Python scalars.

In [5]:
import numpy as np
import tensorflow as tf

rand_array = np.asarray([[3.3, 4.4, 5.5], [3.3, 4.4, 5.5], [3.3, 4.4, 5.5]])

rand_tensor = tf.convert_to_tensor(rand_array, dtype=tf.float32)

rand_tensor

<tf.Tensor 'Const:0' shape=(3, 3) dtype=float32>

## dtypes
- [Data Types](https://www.tensorflow.org/versions/r0.11/resources/dims_types.html#data-types)
- In addition to dimensionality, Tensors have a data type.
- tf.float32 has gives us decimal places with 32 bits of precision, rather than the previous data types 8 bits. 
- This will become important when we start to work with neural networks, as we'll need all of those extra possible values!

### = tf.float32...

In [ ]:
# tf.float32: 32 bits floating point.
tf.constant(99.9, dtype=tf.float32, shape=None, name='Const')

In [ ]:
# tf.float32: 64 bits floating point.
tf.constant(99.9, dtype=tf.float64, shape=None, name='Const')

### = tf.uint8...

In [5]:
# tf.uint8: 8 bits unsigned integer.
tf.constant(99.9, dtype=tf.uint8, shape=None, name='Const')

<tf.Tensor 'Const:0' shape=() dtype=float32>

### = tf.string...

In [7]:
# tf.string: Variable length byte arrays. Each element of a Tensor is a byte array.
tf.constant(["file0", "file1"], dtype=tf.string, shape=None, name='Const')

<tf.Tensor 'Const_1:0' shape=(2,) dtype=string>

# Sharing
- When building complex models we often need to share large sets of variables.
- TensorFlow provides a Variable Scope mechanism that allows to easily share named variables while constructing a graph.

## Scope

### = tf.variable_scope()...
- [Variable Scope Example](https://www.tensorflow.org/versions/r0.11/how_tos/variable_scope/index.html#variable-scope-example)
- The function tf.get_variable() is used to get or create a variable instead of a direct call to tf.Variable. 
- It uses an initializer instead of passing the value directly, as in tf.Variable. 
- An initializer is a function that takes the shape and provides a tensor with that shape.

Nesting variable scopes appends their names in a way analogous to how directories work:

### = tf.get_variable_scope()...

In [ ]:
with tf.variable_scope("foo"):
    v = tf.get_variable("v", [1])
    tf.get_variable_scope().reuse_variables()
    v1 = tf.get_variable("v", [1])
assert v1 is v

## Variables

### reuse_variables()
- tf.get_variable() checks that already existing variables are not shared by accident. If you want to share them, you need to specify it by setting reuse_variables() as follows.

### = tf.get_variable()...
- [tf.get_variable(name, shape, dtype, initializer)](https://www.tensorflow.org/versions/r0.11/how_tos/variable_scope/index.html#understanding-tf-get-variable)
- get_variable() does one of two things depending on the scope it is called in.
 - **If reuse is false:** Then we get a newly created tf.Variable()
 - **If reuse is true:** Then the call will search for an already existing variable with name equal to the current variable scope name + the provided name. If no such variable exists, a ValueError will be raised.

## Initializers
- An initializer is a function that takes the shape and provides a tensor with that shape.

### = tf.random_normal_initializer()...

### Example

- This function uses short names "weights" and "biases". We'd like to use it for both conv1 and conv2, but the variables need to have different names. This is where tf.variable_scope() comes into play: it pushes a namespace for variables.

# Device
- [Device Placement](https://www.tensorflow.org/versions/r0.11/how_tos/variables/index.html#device-placement)
- A variable can be pinned to a particular device when it is created, using a with tf.device(...): block:

### = tf.device()...