# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Class-tf.Operation" data-toc-modified-id="Class-tf.Operation-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Class tf.Operation</a></div><div class="lev3 toc-item"><a href="#=-Names..." data-toc-modified-id="=-Names...-1.0.1"><span class="toc-item-num">1.0.1&nbsp;&nbsp;</span>= Names...</a></div><div class="lev3 toc-item"><a href="#=-Inputs/Outputs..." data-toc-modified-id="=-Inputs/Outputs...-1.0.2"><span class="toc-item-num">1.0.2&nbsp;&nbsp;</span>= Inputs/Outputs...</a></div><div class="lev3 toc-item"><a href="#=-Executing..." data-toc-modified-id="=-Executing...-1.0.3"><span class="toc-item-num">1.0.3&nbsp;&nbsp;</span>= Executing...</a></div><div class="lev1 toc-item"><a href="#Operations" data-toc-modified-id="Operations-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Operations</a></div><div class="lev3 toc-item"><a href="#=-tf.nn.xw_plus_b()..." data-toc-modified-id="=-tf.nn.xw_plus_b()...-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>= tf.nn.xw_plus_b()...</a></div><div class="lev3 toc-item"><a href="#=-tf.unique_with_counts()..." data-toc-modified-id="=-tf.unique_with_counts()...-2.0.2"><span class="toc-item-num">2.0.2&nbsp;&nbsp;</span>= tf.unique_with_counts()...</a></div><div class="lev1 toc-item"><a href="#Basic-Math" data-toc-modified-id="Basic-Math-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Basic Math</a></div><div class="lev3 toc-item"><a href="#=-tf.mul()..." data-toc-modified-id="=-tf.mul()...-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span>= tf.mul()...</a></div><div class="lev3 toc-item"><a href="#=-tf.pow()..." data-toc-modified-id="=-tf.pow()...-3.0.2"><span class="toc-item-num">3.0.2&nbsp;&nbsp;</span>= tf.pow()...</a></div><div class="lev3 toc-item"><a href="#=-tf.square()..." data-toc-modified-id="=-tf.square()...-3.0.3"><span class="toc-item-num">3.0.3&nbsp;&nbsp;</span>= tf.square()...</a></div><div class="lev3 toc-item"><a href="#=-tf.sqrt()..." data-toc-modified-id="=-tf.sqrt()...-3.0.4"><span class="toc-item-num">3.0.4&nbsp;&nbsp;</span>= tf.sqrt()...</a></div><div class="lev3 toc-item"><a href="#=-tf.squared_difference()..." data-toc-modified-id="=-tf.squared_difference()...-3.0.5"><span class="toc-item-num">3.0.5&nbsp;&nbsp;</span>= tf.squared_difference()...</a></div><div class="lev1 toc-item"><a href="#Matrix" data-toc-modified-id="Matrix-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Matrix</a></div><div class="lev3 toc-item"><a href="#=-tf.scalar_mul()..." data-toc-modified-id="=-tf.scalar_mul()...-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span>= tf.scalar_mul()...</a></div><div class="lev3 toc-item"><a href="#=-tf.matmul()..." data-toc-modified-id="=-tf.matmul()...-4.0.2"><span class="toc-item-num">4.0.2&nbsp;&nbsp;</span>= tf.matmul()...</a></div><div class="lev3 toc-item"><a href="#=-tf.matrix_inverse()..." data-toc-modified-id="=-tf.matrix_inverse()...-4.0.3"><span class="toc-item-num">4.0.3&nbsp;&nbsp;</span>= tf.matrix_inverse()...</a></div><div class="lev3 toc-item"><a href="#tf.transpose()..." data-toc-modified-id="tf.transpose()...-4.0.4"><span class="toc-item-num">4.0.4&nbsp;&nbsp;</span>tf.transpose()...</a></div><div class="lev1 toc-item"><a href="#Reduction" data-toc-modified-id="Reduction-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Reduction</a></div><div class="lev3 toc-item"><a href="#=-tf.reduce_sum()..." data-toc-modified-id="=-tf.reduce_sum()...-5.0.1"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span>= tf.reduce_sum()...</a></div><div class="lev3 toc-item"><a href="#=-tf.reduce_mean()..." data-toc-modified-id="=-tf.reduce_mean()...-5.0.2"><span class="toc-item-num">5.0.2&nbsp;&nbsp;</span>= tf.reduce_mean()...</a></div><div class="lev1 toc-item"><a href="#Control-Flow" data-toc-modified-id="Control-Flow-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Control Flow</a></div><div class="lev3 toc-item"><a href="#=-tf.logical_or()..." data-toc-modified-id="=-tf.logical_or()...-6.0.1"><span class="toc-item-num">6.0.1&nbsp;&nbsp;</span>= tf.logical_or()...</a></div><div class="lev1 toc-item"><a href="#Comparison" data-toc-modified-id="Comparison-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Comparison</a></div><div class="lev3 toc-item"><a href="#=-tf.equal()..." data-toc-modified-id="=-tf.equal()...-7.0.1"><span class="toc-item-num">7.0.1&nbsp;&nbsp;</span>= tf.equal()...</a></div><div class="lev1 toc-item"><a href="#Debugging" data-toc-modified-id="Debugging-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Debugging</a></div><div class="lev3 toc-item"><a href="#=-tf.is_nan()..." data-toc-modified-id="=-tf.is_nan()...-8.0.1"><span class="toc-item-num">8.0.1&nbsp;&nbsp;</span>= tf.is_nan()...</a></div><div class="lev3 toc-item"><a href="#=-tf.Print()..." data-toc-modified-id="=-tf.Print()...-8.0.2"><span class="toc-item-num">8.0.2&nbsp;&nbsp;</span>= tf.Print()...</a></div>

In [2]:
# Import tensorflow
import tensorflow as tf

# Class tf.Operation
- [class tf.Operation](https://www.tensorflow.org/versions/r0.11/api_docs/python/framework.html#Operation)
- An Operation is a node in a TensorFlow Graph that takes zero or more Tensor objects as input, and produces zero or more Tensor objects as output.

### = Names...

In [8]:
# The full name of this operation.
tf.Operation.name

In [9]:
# The name of the device to which this op has been assigned, if any.
tf.Operation.device

In [10]:
# The Graph that contains this operation.
tf.Operation.graph

### = Inputs/Outputs...

In [11]:
# The list of Tensor objects representing the data inputs of this op.
tf.Operation.inputs

In [12]:
# The list of Tensor objects representing the outputs of this op.
tf.Operation.outputs

### = Executing...

In [ ]:
# Runs this operation in a Session.
tf.Operation.run(feed_dict=None, session=None)

In [13]:
# Returns the call stack from when this operation was constructed.
tf.Operation.traceback

# Operations

### = tf.nn.xw_plus_b()...
[Method exists but is not documented](https://github.com/tensorflow/tensorflow/issues/1434)

In [ ]:
# Activity
a2 = tf.nn.xw_plus_b(h1, w2, b2)

### = tf.unique_with_counts()...
- [tf.unique_with_counts(x, out_idx=None, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#unique_with_counts)

# Basic Math
- [Basic Math](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#basic-math-functions)

### = tf.mul()...
- [tf.mul(x, y, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#mul)

In [4]:
a = tf.constant(3)
print(a.get_shape)
b = tf.constant(5)
print(b.get_shape)

m = tf.mul(a,b)
print(m.get_shape)

with tf.Session() as sess:
    print(m.eval())

3*5

<bound method Tensor.get_shape of <tf.Tensor 'Const_1:0' shape=() dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Const_2:0' shape=() dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Mul:0' shape=() dtype=int32>>
15


15

In [5]:
a = tf.constant([3,2,1])
print(a.get_shape)
b = tf.constant([6,5,4])
print(b.get_shape)

mm = tf.mul(a,b)
print(mm.get_shape)

with tf.Session() as sess:
    print(mm.eval())

6*3, 2*5, 1*4

<bound method Tensor.get_shape of <tf.Tensor 'Const_3:0' shape=(3,) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Const_4:0' shape=(3,) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Mul_1:0' shape=(3,) dtype=int32>>
[18 10  4]


(18, 10, 4)

### = tf.pow()...
- [tf.pow(x, y, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#pow)

In [4]:
# If tensors are the same size it works like they are layed on top of one another
c = tf.constant([[2, 2], [3, 3]])
print(c.get_shape)
d = tf.constant([[8, 16], [2, 3]])
print(d.get_shape)

p = tf.pow(c, d)
print(p.get_shape)


with tf.Session() as sess:
    print(p.eval())

print(2**8, 2**16)
print(3**2, 3**3)

<bound method Tensor.get_shape of <tf.Tensor 'Const_4:0' shape=(2, 2) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Const_5:0' shape=(1, 2) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Pow:0' shape=(2, 2) dtype=int32>>
[[     256    65536]
 [    6561 43046721]]
256 65536
9 27


In [9]:
# If rows are missing in the second array the lone data is squared
c = tf.constant([[2, 2], [3, 3]])
print(c.get_shape)
d = tf.constant([[8, 16]])
print(d.get_shape)

p = tf.pow(c, d)
print(p.get_shape)


with tf.Session() as sess:
    print(p.eval())

print(2**8, 2**16)
print(3**2, 3**3)

<bound method Tensor.get_shape of <tf.Tensor 'Const_13:0' shape=(2, 2) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Const_14:0' shape=(1, 2) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Pow_3:0' shape=(2, 2) dtype=int32>>
[[     256    65536]
 [    6561 43046721]]
256 65536
9 27


### = tf.square()...
- [tf.square(x, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#square)

### = tf.sqrt()...
- [tf.sqrt(x, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#sqrt)

In [ ]:
tf.sqrt(x, name=None)

### = tf.squared_difference()...
- [tf.squared_difference(x, y, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#squared_difference)

# Matrix
- [Matrix Operation](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#matrix-math-functions)

### = tf.scalar_mul()...
- [tf.scalar_mul(scalar, x)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#scalar_mul)

In [ ]:
tf.scalar_mul(scalar, x)

### = tf.matmul()...
- [tf.matmul(a, b, transpose_a=False, transpose_b=False, a_is_sparse=False, b_is_sparse=False, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#matmul)

In [6]:
# 2-D tensor `a`
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print(a.get_shape)
                                                      
# 2-D tensor `b`
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
print(b.get_shape)

mm = tf.matmul(a, b)
print(mm.get_shape)

with tf.Session() as sess:
    print(mm.eval())

<bound method Tensor.get_shape of <tf.Tensor 'Const_5:0' shape=(2, 3) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Const_6:0' shape=(3, 2) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'MatMul:0' shape=(2, 2) dtype=int32>>
[[ 58  64]
 [139 154]]


### = tf.matrix_inverse()...
- [tf.matrix_inverse(input, adjoint=None, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#matrix_inverse)
- This is an operation that returns our identity matrix of horizontal ones.

### = tf.transpose()...
- [tf.transpose(a, perm=None, name='transpose')](https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#transpose)
- Transposes a. Permutes the dimensions according to perm.
- The returned tensor's dimension i will correspond to the input dimension perm[i]. If perm is not given, it is set to (n-1...0), where n is the rank of the input tensor. Hence by default, this operation performs a regular matrix transpose on 2-D input Tensors.

# Reduction
- [Reduction Operations](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#reduction)

### = tf.reduce_sum()...
- [tf.reduce_sum(input_tensor, reduction_indices=None, keep_dims=False, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#reduce_sum)
- Computes the sum of elements across along the dimensions given in reduction_indices.
- Unless keep_dims is true, the rank of the tensor is reduced by 1 for each entry in reduction_indices.
- If keep_dims is true, the reduced dimensions are retained with length 1.

In [16]:
e = tf.constant([[1, 1, 1],
                 [1, 1, 1]])
print(e.get_shape)

#flattens all rows then sums
f = tf.reduce_sum(e) # ==> 6
f = tf.reduce_sum(e, 0) # ==> [2, 2, 2]
f = tf.reduce_sum(e, 1) # ==> [3, 3]
#f = tf.reduce_sum(e, 1, keep_dims=True) # ==> [[3], [3]]
#f = tf.reduce_sum(e, [0, 1]) # ==> 6

with tf.Session() as sess:
    print(f.eval())

<bound method Tensor.get_shape of <tf.Tensor 'Const_20:0' shape=(2, 3) dtype=int32>>
[3 3]


### = tf.reduce_mean()...
- [tf.reduce_mean(input_tensor, reduction_indices=None, keep_dims=False, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html#reduce_mean)

# Logical Operators
- [Logical Operators](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#logical-operators) 

### = tf.logical_or()...
- [tf.logical_or(x, y, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#logical_or)

tf.logical_or(x, y, name=None)

# Comparison
- [Comparison Operators](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#comparison-operators)

### = tf.equal()...
- [tf.equal(x, y, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#equal)

# Debugging
- [Debugging Operations](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#debugging-operations)

### = tf.is_nan()...
- [tf.is_nan(x, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#is_nan)

In [ ]:
tf.is_nan(x, name=None)

### = tf.Print()...
- [tf.Print(input_, data, message=None, first_n=None, summarize=None, name=None)](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#Print)

In [ ]:
# Prints a list of tensors.
tf.Print(input_, data, message=None, first_n=None, summarize=None, name=None)